name: Create Branch on Issue

on:
  issues:
    types: [opened]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = context.payload.issue;
            const title = issue.title;
            const match = title.match(/\[(.*?)\] #(\d+)/);
            if (match) {
              const prefix = match[1].replace(/ /g, '-');
              const number = match[2];
              const branchName = `${prefix}/#${number}`;
              
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/heads/${branchName}`,
                sha: context.sha
              });
              
              console.log(`Created branch: ${branchName}`);
            } else {
              console.log('Branch name format not found in issue title');
            }
